environment: production

domain: w3f.tech
matrixDomain: web3.foundation

brand: "Web3 Foundation"

port: 8080

image:
  repo: bubuntux/riot-web
  tag: v1.7.25

resources:
  limits:
    cpu: 300m
    memory: 300Mi
  requests:
    cpu: 100m
    memory: 100Mi  
